### ISSUE TITLE
Response me pls

### ISSUE THREAD

**Issue by chonma1988** [Pymmdrza/xBrainWallet#4]
@Pymmdrza I tried to contact you  i have paid my order chonmaphoom.si@gmail.com please help and get response

**Comment by chonma1988** [comment]
![Screenshot_2024-07-03-10-05-51-919_com binance dev](https://github.com/Pymmdrza/xBrainWallet/assets/165540057/e8461d2f-ca40-4b6f-9d5e-4af59c6364ce)
![Screenshot_2024-07-03-10-04-38-328_com android chrome](https://github.com/Pymmdrza/xBrainWallet/assets/165540057/c056f248-884c-4874-b7f7-1c1b5736ee68)
![Screenshot_2024-07-03-10-06-07-699_com binance dev](https://github.com/Pymmdrza/xBrainWallet/assets/165540057/cc746896-719e-4f39-b2a4-910f95d1cd65)

**Comment by Pymmdrza** [comment]
Are u spammer
